name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"
          fetch-depth: 0
      - name: Inject version into mainpage.dox
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0-untagged")
          TAG=$(echo "$TAG" | sed 's/^v//')
          echo "Using version: $TAG"
          test -f docs/mainpage.dox || { echo "mainpage.dox not found!"; exit 1; }
          sed -i "0,/VERSION_PLACEHOLDER/s//$TAG/" docs/mainpage.dox
      - name: Generate Documentation
        uses: mattnotmitt/doxygen-action@edge
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: docs/html
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
